name: 'Create Release from PR Title'
description: 'Create a release with a tag equal to the PR title with spaces removed'
author: 'Your Name'
branding:
  icon: 'package'
  color: 'green'
inputs:
  title:
    description: 'PR title'
    required: true
  token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
